### ISSUE TITLE
Parallel Cleaver2

### ISSUE THREAD

**Issue by moritzdannhauer** [SCIInstitute/Cleaver2#10]
After cleaver2 works stable on the head segmentation (Shankar is fixing the flat tets issue) we provided I want to implement a SCIRun5 module that interfaces with it. I hope cleaver2 was designed to work as a library and need a detailed description of the interface. 

Future:
If we get this done ... at some point in the future it would be nice that cleaver2 runs in parallel so that the most important aspects (to be actually useful) are met:
1) generate a mesh with a reasonable number of elements (this number should be much smaller than cleaver1, maybe a number estimate can get determined or chosen by the user) 
2) in a reasonable timeframe (in the range of minutes) - e.g. you should wait not more than 15min for a normal head dataset
It might be essential that the parallel part is implemented directly in the cleaver 2 library and not SCIRun5

**Comment by jonbronson** [comment]
While still possible, this is not currently on the roadmap for cleaver.
