### ISSUE TITLE
Mesh quality functions near quadruple points create flat tets

### ISSUE THREAD

**Issue by brigb123** [SCIInstitute/Cleaver2#3]
Two 200 line functions that determine interface points that are close to an edge or face of the background mesh, and modify the mesh to make sure the quality is still maintained.

**Comment by brigb123** [comment]
Hey Jon, what's the status for this issue?

**Comment by brigb123** [comment]
Currently being tested and debugged by Shankar

**Comment by brigb123** [comment]
Jon's new code helps decrease the number of flat tets, but the issue still exists.

**Comment by zaracay** [comment]
Flat tets appear to align with major axes.  For example, my hearts generally share a long axis (from base to apex) with the z axis.  The majority of flat tets that I see are in the xy plane on the base, but I also see them on the xz and yz planes...a lot

<img width="438" alt="xy plane" src="https://cloud.githubusercontent.com/assets/3486194/19487110/8838e4aa-951e-11e6-8eb1-3e37fdb7cb17.png">

**Comment by brocktice** [comment]
Is there a workaround for this? Is it related to the alpha value?

**Comment by jonbronson** [comment]
I believe this issue has now been fixed by commit 59725cbe11c8e0644d167de74e076188760e13b8 

It was alpha value related, see commit for more details.

**Comment by brocktice** [comment]
Excellent, will test.
