### ISSUE TITLE
Shader requirements don't allow graphics to display on mac

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/Cleaver2#34]
Error:

QOpenGLShader::compile(Vertex): ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:3: 'layout' : syntax error: syntax error

*** Problematic Vertex shader source code ***
#version 330
#define lowp
#define mediump
#define highp
#line 2
layout (location = 0) in vec3 aPos;
layout (location = 1) in vec3 aColor;
uniform mat4 uRotation;
uniform float uAspect;
uniform float uWidth;
out vec4 oColor;

System:
OS X 10.10.5
NVIDIA GeForce GT 755M 1024 MB

(about a 3 year old iMac)

**Comment by brigb123** [comment]
done here 6e730a84f5df09aa4f83d52c8656ab69bdd751ff
