### ISSUE TITLE
Avoid the need to snap triple/quad points back into tet

### ISSUE THREAD

**Issue by brigb123** [SCIInstitute/Cleaver2#39]
The scenario is that when the triple or quadruple point is estimated (solving a linear equation) for a tet, it is sometimes outside the tet, requiring a step "snap" to put the point back into the tet. The hypothesis is that sometimes the wrong edge/face is selected to snap back to, creating a flat tet. If the estimated triple or quadruple could be guaranteed to not be outside the element, the snap step can be skipped and the created flat tets would no longer exist.

**Comment by jonbronson** [comment]
Unfortunately the mathematics of the 4 point material interpolation allow for these points to exist outside of the tet. Resolving them is a step we have to take.
