### ISSUE TITLE
Implement a tightening algorithm to preserve small features.

### ISSUE THREAD

**Issue by brigb123** [SCIInstitute/Cleaver2#42]
This would be great if done using ITK tools.

**Comment by zaracay** [comment]
One of the big differences between Cleaver and BioMesh is the preservation of these small features.  I'm not sure if it is as much a tightening thing (which I see of as more of a smoothing feature) or if it is a sizing field construction thing, or even a cleaving thing.  But here is an example of what should be fixed for more people to use it.

Notice the circled vessel in both BioMesh and Cleaver outputs.  In the BioMesh output, the vessel is intact.  In the Cleaver output, it is not.  
![biomesh_vessels](https://cloud.githubusercontent.com/assets/3486194/17941111/2198f23a-69ef-11e6-92f0-1f34e8470d37.png)
![cleaver_vessels](https://cloud.githubusercontent.com/assets/3486194/17941113/21aa3310-69ef-11e6-828a-47989c3a1664.png)

**Comment by jonbronson** [comment]
This is a sizing field issue. Cleaver is "dumb" with respect to the size of features and can only capture features large enough to be on the background mesh.
