### ISSUE TITLE
Cleaver2 creates a 'bumpy' surface where the input is perfectly flat, rounds edges

### ISSUE THREAD

**Issue by brocktice** [SCIInstitute/Cleaver2#52]
We need distinct surfaces with sharp edges for a particular purpose. Other meshing tools we have used leave a flat surface where one is input. Cleaver2 appears to round the edges and leave bumps on the surface.

Is this always going to be the case because of the mechanism by which it meshes, or is there a way with parameters (or changes to code) to change this?

See example below looking at the ventricles of a heart, where the base is cut off it is expected to be flat, but is not.

![cleaver2_mesh_surface](https://cloud.githubusercontent.com/assets/467292/26177919/f6d67968-3b18-11e7-8208-14ed79c0233d.png)

**Comment by jonbronson** [comment]
Cleaver is capable of capturing flat surfaces as long as the indicator functions passed in accurately represent those flat features. Sharp features on the other hand (e.g. right angle corner) will be rounded off. There's potential work to extend Cleaver to handle sharp features, but that would be a fair amount of work to accomplish. Please provide more information if this is not helpful.
