### ISSUE TITLE
Sizing Field: Feature Request -- Add export to File menu

### ISSUE THREAD

**Issue by zaracay** [SCIInstitute/Cleaver2#59]
The File menu offers an export mesh option, but no other export options.  Sizing field would be the most valuable, but other options could include surfaces and dihedral angles.

**Comment by jonbronson** [comment]
You can already export any field in the data view by right-clicking and selecting Export field.
Exporting surface mesh should be straight forward as we already support exporting to PLY via command line.
For dihedral angles,  would you want those angles as data on the nodes in the output? Or as a separate file. What's the use case for that output?
