### ISSUE TITLE
export sizing field crashes when file ending is not specified by user

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Cleaver2#63]
In the Cleaver gui, when the export sizing field option is selected, the file dialogue is brought up. If the file name is not a *.nrrd, cleaver will crash.  The default file name does not have it, therefore it will crash unless it is added.  If the file ending is something else, it will also crash.  

Since nrrd is the only format for this function, it should add it to the file name if it is not already there.

os x 10.12
cleaver 2.3

**Comment by allywarner** [comment]
Verified.
