### ISSUE TITLE
sigma value may not change with inputs

### ISSUE THREAD

**Issue by jessdtate** [SCIInstitute/Cleaver2#64]
The sigma smoothing parameter doesn't seem to affect the the solution.  The parameter appears to be hard coded and based on world units.  When running a volume of size 5 with with 128x128x128 voxels, the result is over smoothed.  When running on the command line, I get the following error no matter what value is used in the -B flag:

WARNING: In /Users/jess/software/ITK/Modules/Core/Common/include/itkGaussianOperator.hxx, line 61
GaussianOperator (0x7fd3b8d02130): Kernel size has exceeded the specified maximum width of 32 and has been truncated to 33 elements.  You can raise the maximum width using the SetMaximumKernelWidth method.

Scaling the volume reduces the volume.  Here are images for different sized volumes (5, 50, 500)

![medium_5_0_sigma](https://user-images.githubusercontent.com/3484631/34900601-8693e4ac-f7be-11e7-937f-a9cfaeba13dc.png)
![medium_50_0_sigma](https://user-images.githubusercontent.com/3484631/34900602-86a4c1a0-f7be-11e7-8a89-d86f2e48b02b.png)
![medium_500_0_sigma](https://user-images.githubusercontent.com/3484631/34900603-86bd2e5c-f7be-11e7-9ff9-73c4aa1e1c63.png)

increasing or decreasing the sigma, either using the ui or the cli, does not produce a discernible change in the result.

**Comment by jessdtate** [comment]
When the size is large enough, increasing the sigma size can have an effect.  This may be a problem with converting the float to an int.

**Comment by jessdtate** [comment]
[medium_5_seg.nrrd.zip](https://github.com/SCIInstitute/Cleaver2/files/2989980/medium_5_seg.nrrd.zip)
[medium_5.nrrd.zip](https://github.com/SCIInstitute/Cleaver2/files/2989981/medium_5.nrrd.zip)
[medium_500_seg.nrrd.zip](https://github.com/SCIInstitute/Cleaver2/files/2989982/medium_500_seg.nrrd.zip)
[medium_500.nrrd.zip](https://github.com/SCIInstitute/Cleaver2/files/2989983/medium_500.nrrd.zip)
Here are some example data that highlight the sigma smoothing based on size.

**Comment by allywarner** [comment]
Sigma is not available on command line. - Wilson
