### ISSUE TITLE
Feature Request: Cleaver import and remesh of surfaces

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/Cleaver2#70]

**Comment by bzenger** [comment]
Currently, tetgen (possibly other meshing software) can take in multiple surfaces (as a surface mesh with nodes and triangular elements) and remesh the surfaces together to make one complete mesh using the nodes from the surfaces to create new elements. 

However, cleaver does not have this functionality. It would be nice to be able to import current surface meshes as independent meshes and remesh them to be an entire mesh.

**Comment by allywarner** [comment]
Hi Brian,

You can make indicator functions from these surfaces in SCIRun and using the interface with Cleaver to make a Cleaver mesh.

Ally Warner

I use she/her/hers pronouns - learn more about this here.
<https://uwm.edu/lgbtrc/support/gender-pronouns/>

**Comment by bzenger** [comment]
whoa whoa whoa. Hold on. This is awesome. I will test this soon.
