### ISSUE TITLE
Meshes not right size, location, or value. 

### ISSUE THREAD

**Issue by bzenger** [SCIInstitute/Cleaver2#79]
Please follow these instructions for your issue to be worked on:

### Description

The new version of cleaver is scaling and creating meshes not like the old version, and that do not match the original segmentation. This is not a simple "translation" problem but something much more significant. I am unaware of how to fix this or why it would be.

See in the screen shots attached below. Red is the old version of cleaver, blue is the new version of cleaver. 

Also, the "foreground" mesh number is now set to 0 and the background is set to 1, which is annoying for our programs that use the old format. 
[Archive.zip](https://github.com/SCIInstitute/Cleaver2/files/3193266/Archive.zip)

<img width="556" alt="image" src="https://user-images.githubusercontent.com/30505095/57958667-8fa40d00-78ce-11e9-98f3-a0c3ee3f3d2b.png">

### Steps to Reproduce
 
I created a simple segmentation of a cylinder and meshed them with identical (default) settings of both cleaver versions. 

Important notes: 
1. The cleaver loading of the file took much longer in the newer version than the older version. I am not sure why that would be. Cleaver also took significantly longer to mesh in the newer version than the older version. By significant I mean a difference of several minutes to create the mesh. 
2. Loaded these identical files in as .nrrd files of a segmentation 
3. Cleaved, meshed, and saved them out as .mat files for matlab (according to the viewer) 
** This was all done in the GUI, not command line ** 

### Versions

Mac OS: 10.13.6
Cleaver Versions: 2.3.1 and 2.4 (latest master) 
ITK 4.13 
QT5.9

**Comment by allywarner** [comment]
Should be fixed with with latest PR. Although, Cleaver is still running slower on OSX. Release to follow.
