### ISSUE TITLE
Consistency in geometry information when using sizing field

### ISSUE THREAD

**Issue by A-ep93** [SCIInstitute/Cleaver2#96]
Hello,
I  am using cleaver through segment mesher in slicer and we faced a problem which is also discussed [here](https://discourse.slicer.org/t/meshing-a-model-with-different-parts/14168/7?u=aep93) 
We want to use sizing field to manually determine the regions where we want coarse or fine mesh however we were not able to do this. One reason can be this: Cleaver makes changes to the volume size (adds padding) and discards spacing, origin, and axis direction information when importing/exporting sizing fields, so it is hard to know what image geometry cleaver expects.
We think this should be fixed so that cleaver uses image geometry information (origin, spacing, axis directions) consistently in all inputs and outputs.

**Comment by jessdtate** [comment]
Thanks @A-ep93. As far as I know, the current Cleaver module in Slice uses Cleaver 1.0.   Could you clarify whether you have tested this in Slicer or  with the newest version of Cleaver2?  We have made some effort to address this concern (#81).

**Comment by A-ep93** [comment]
Thanks for your response @jessdtate. Actually, we did this with the  [Segmentmesher](https://github.com/lassoan/SlicerSegmentMesher) module of slicer that uses cleaver 2.

**Comment by jessdtate** [comment]
Thanks for the clarification.  The fork that Segmentmesher is using for Cleaver is 3 years old (https://github.com/lassoan/Cleaver2). I'm not sure what the best way forward with this.  You could try building the module against this fork, or perhaps @lassoan can update their fork? We can look into merging some of the build changes in that fork, but it may be inconsistent with future plans for Cleaver.

**Comment by lassoan** [comment]
I haven't updated Cleaver version in Slicer because I only saw cosmetic changes, but maybe I missed important fixes. It is not a problem to update the Cleaver2 git hash in SlicerSegmentMesher at all. I'll also remove the old Clever1 extension to reduce confusion.

**Comment by A-ep93** [comment]
Thank you very much @lassoan. That is great. Can you kindly please let me know when you will be able to update the cleaver2 for segmentmesher?

**Comment by fluviolobo** [comment]
This would also be of great interest to my team @lassoan. Will an update be posted on the weekly summary emails?

**Comment by lassoan** [comment]
3D Slicer's SegmentMesher extension now uses latest version of Cleaver2.
